# Workflow to build the environment
name: ci
on: 
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
       - name: Checkout the repository on ubuntu runner
         uses: actions/checkout@v4
       - name: Install Java version 11
         uses: actions/setup-java@v4
         with:
           distribution: 'temurin' # See 'Supported distributions' for available options
           java-version: '11'
       - name: Build with Maven
         run: |
           mvn package
           ls -l
       # - name: Upload Artifact
       #   uses: actions/upload-artifact@v4
       #   with:
       #     name: devops-war
       #     path: target/devops.war
# u can download the artefact on ur custom runner using download artefact action ... or build docker image like below and deploy with that..

# https://github.com/marketplace/actions/build-and-push-docker-images

       - name: Set up QEMU
         uses: docker/setup-qemu-action@v3
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v3
       - name: Login to Docker Hub
         uses: docker/login-action@v3
         with:
           username: ${{ secrets.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_TOKEN }}
       - name: Build and push
         uses: docker/build-push-action@v5
         with:
           context: .
           push: true
           tags: ramann123/myimage:GAimage
      



